name: Build UltraQR
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-ultraqr:
    name: Build and upload release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Build ultraqr
      run: cd ultraqr && go build .

    - uses: actions/upload-artifact@v4
      with:
        name: ultraqr
        path: ultraqr/ultraqr

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ultraqr/ultraqr
